services:
  tracking-cano:
    image: tracking-cano
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tracking-cano
    env_file:
      - .env
    environment:
      - RTSP_URL=${RTSP_URL}
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
    command: ["python", "main.py", "--live"]
    restart: unless-stopped
